[tool.black]
line-length = 100
target-version = ['py311']

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "UP", "B", "A", "C4", "DTZ", "T20"]
ignore = ["N999", "T201"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["E501", "I001", "F401", "F811", "Q000"]

[tool.mypy]
python_version = 3.11
ignore_missing_imports = true
strict = true
explicit_package_bases = true

[[tool.mypy.overrides]]
module = [
	"tests.*",
]
ignore_errors = true


[tool.isort]
profile = "black"
line_length = 100
